version: '1.0'
stages:
  - prepare
  - test
  - integration
  - build
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: master
    git: GitHub
  MyUnitTests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
  Integration:
    title: Integration test
    stage: integration
    image: maven:3.5.2-jdk-8-alpine
    commands:
     - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository verify      
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: '${{CF_REPO_NAME}}'
    working_directory: ./
    tag: 'non-multi-stage'
    dockerfile: Dockerfile
  KubernetesCanaryDeployment:
    title: 'Deploying new version ${{CF_SHORT_REVISION}}'
    stage: deploy
    type: k8s-canary-deployment
    arguments:
      WORKING_VOLUME: .
      SERVICE_NAME: '${{SERVICE_NAME}}'
      DEPLOYMENT_NAME: '${{CF_REPO_NAME}}'
      TRAFFIC_INCREMENT: '${{TRAFFIC_INCREMENT}}'
      NEW_VERSION: '${{NEW_VERSION}}'
      SLEEP_SECONDS: '${{SLEEP_SECONDS}}'
      NAMESPACE: 'demo-namespace-1'
      KUBE_CONTEXT: 'demo-cluster-2'

  
